name: Secure End-End for dotnet and C#
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x
        - name: Install dependencies
          run: dotnet restore


